//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Funds.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_FundsEntities : DbContext
    {
        public db_FundsEntities()
            : base("name=db_FundsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblLoginMaster> tblLoginMasters { get; set; }
        public DbSet<tblLoan> tblLoans { get; set; }
    }
}
