//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Funds.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int C_Id { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AdhaarNo { get; set; }
        public string PanNo { get; set; }
    }
}
