//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Funds.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyCollection
    {
        public int DailyCollectionId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> LoanNoId { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<int> LoanDuration { get; set; }
        public Nullable<int> PerDayInstallment { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<int> DaysPaid { get; set; }
        public Nullable<int> RemainingDays { get; set; }
        public Nullable<System.DateTime> TodaysDate { get; set; }
        public Nullable<decimal> AmountPaidToday { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
