//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Funds.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoan
    {
        public int LoanId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<int> LoanDurationDays { get; set; }
        public Nullable<decimal> LoanInterest { get; set; }
        public string DeductAmount { get; set; }
        public string AmountGivenToCustomer { get; set; }
        public string LoanDurationWithMonths { get; set; }
        public string DailyReturn { get; set; }
        public string TotalPayable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
